### PR TITLE
fix now that fits files are no longer gzipped

### PR DESCRIPTION
**Pull request by villarrealas**
Modification to the job success check now that we are no longer outputting gzip files and checkpoints are no longer being removed.

### CODE REVIEW

**Comment by benclifford** [comment]
I think this will incorrectly detect work as done if a partially written fits file exists?

**Comment by villarrealas** [comment]
As far as we can tell, there is no current high-speed workaround for that. There is some circumstantial evidence that the writing of a .fits file with astropy should be atomic, which should mean that case does not come up.

**Comment by benclifford** [comment]
from some further poking, there's some path weirdness that I've chatted with @villarrealas on the slack channel about, and he's going to investigate before further review.

**Comment by benclifford** [comment]
@villarrealas  - is this PR still relevant? I can't remember.

**Pull request closed without merging**
